### ISSUE TITLE
Invoice API to use a Database instead of In-memory values

### ISSUE THREAD

**Issue by lucassouzavieira** [utilitywarehouse/associate-tech-test#3]
## Step 1 - Define Storage interface

Given that we are now able to connect to a Postgres instance running inside a container and correctly create the necessary tables through migrations, we need to change the Invoices API to use the Postgres as data storage. To do so, create a `InvoiceStorage` [interface](https://www.alexedwards.net/blog/interfaces-explained) that contains five methods:

- `GetAll` that receives no arguments an return a slice of `Invoice` and an `error`.
- `GetInvoice` that receives an integer as argument and returns one `Invoice` and an `error`.
- `CreateInvoice` that receives two `string` arguments: Invoice Type and Amount. The method should return the created `Invoice`, if the creation was successful and an `error`.
- `UpdateInvoice` that receives one integer argument - Invoice ID - and two `string` arguments: Invoice Type and Amount. The method needs to return an `error`.
- `DeleteInvoice` that receives an integer as argument and returns an `error`.

The invoice type was defined as follow:
```go
type Invoice struct {
	InvoiceID int     `json:"invoiceid"`
	Type      string  `json:"type"`
	Amount    float64 `json:"amount"`
}
```

## Step 2 - Define the Postgres implementation of the Storage interface

After the `InvoiceStorage` interface was created, you need to create a concrete implementation for it. See the example bellow of a possible concrete implementation for a Postgres database.

```go
type PostgresInvoiceStorage struct {
	db *sql.DB
}
```

After creating the struct, add a method to initialise it. The method needs to receive a `sql.DB` instance. [Note that you may to use the instance already defined](https://github.com/utilitywarehouse/associate-tech-test/blob/3c4ee6c73cb2131aa4aeb09183c459f809de52d9/main.go#L153) for the connection and migration steps.

The initialisation method should have the following [signature](https://go101.org/article/function.html). 

```go
func NewPostgresInvoiceStorage(db *sql.DB) *PostgresInvoiceStorage
```

## Step 3 - Implement the `GetAll` method for the Postgres implementation

Now that we have defined the necessary types, it's time to write the methods of Postgres implementation of `InvoiceStorage`. Start by doing the `GetAll` method, as it doesn't requires any parameters into it's SQL query.

```go
func (storage *PostgresInvoiceStorage) GetAll() ([]Invoice, error) {
	selectStatement := "SELECT * FROM invoices;"
	rows, err := storage.db.Query(selectStatement)
	if err != nil {
		return []Invoice{}, err
	}

	invoices := make([]Invoice, 0) // Slice to store invoices
	defer rows.Close()
	for rows.Next() {
		var invoice Invoice

		err := rows.Scan(&invoice.InvoiceID, &invoice.Type, &invoice.Amount)
		if err != nil {
			return []Invoice{}, fmt.Errorf("failed to get invoice data: %w", err)
		}

		// We correctly read the invoice data.
		invoices = append(invoices, invoice)
	}

	return invoices, nil
}
```

Resources:
- [database/sql](https://pkg.go.dev/database/sql)

>💡 Tip: you can [panic](https://gobyexample.com/panic) or return empty or nil values for the other methods until you can implement them.

## Step 4 - Change the `getInvoices` function to get Invoices from Database

After accomplishing the last steps, change the function that returns all the invoices - `getInvoices` to return data  retrieved from the database instead of relying on pre-defined values.

https://github.com/utilitywarehouse/associate-tech-test/blob/3c4ee6c73cb2131aa4aeb09183c459f809de52d9/main.go#L36-L38

## Step 5 - Implement the `GetInvoice` method for the Postgres implementation

Now that we can retrieve all the invoices, let's implement a method to obtain a single invoice. Please implement the method `GetInvoice`. This method should receive an `InvoiceID` and return a `Invoice` entry with the data obtained from the Database. If the an invoice with the given ID doesn't exists or if the query fails, return the appropriate error.

## Step 6 - Change the `getInvoiceByID` function to get Invoice from Database

After accomplishing the step 5, change the function that returns a particular invoice - `getInvoiceByID` - to return data retrieved from the database instead of relying on pre-defined values.

https://github.com/utilitywarehouse/associate-tech-test/blob/3c4ee6c73cb2131aa4aeb09183c459f809de52d9/main.go#L57-L64

## Step 7 - Implement the `DeleteInvoice` method for the Postgres implementation

Now that we can retrieve all the invoices, let's implement a method to delete an invoice. Please implement the method `DeleteInvoice`. This method should receive an `InvoiceID` and delete the correspondent `Invoice` entry from the Database.

## Step 8 - Change the `deleteInvoiceByID` function to delete invoices from Database

After accomplishing the step 7, change the function that deletes a particular invoice - `deleteInvoiceByID` - to remove an invoice entry from the database instead of removing it from the array with pre-defined values.

https://github.com/utilitywarehouse/associate-tech-test/blob/3c4ee6c73cb2131aa4aeb09183c459f809de52d9/main.go#L113-L130

## Step 9 - Implement the `CreateInvoice` method for the Postgres implementation

Now that we can read and delete data from the database, let's implement a method to add a new entry. Please implement the method `CreateInvoice`. This method should receive two parameters - Type and Amount - and store it on the Database.

## Step 10 - Change the `createInvoice` function to delete invoices from Database

After accomplishing the step 9, change the function that adds a new invoice - `createInvoice` - to create a new invoice entry in the database.

https://github.com/utilitywarehouse/associate-tech-test/blob/3c4ee6c73cb2131aa4aeb09183c459f809de52d9/main.go#L67-L76

## Step 11 - Implement the `UpdateInvoice` method for the Postgres implementation

Now that we can read and delete data from the database, let's implement a method to add a new entry. Please implement the method `CreateInvoice`. This method should receive two parameters - Type and Amount - and store it on the Database.

## Step 12 - Change the `updateInvoice` function to update invoice in the Database

After accomplishing the step 11, change the function that updates an invoice - `updateInvoice` - to update an already existing invoice entry in the database.

https://github.com/utilitywarehouse/associate-tech-test/blob/3c4ee6c73cb2131aa4aeb09183c459f809de52d9/main.go#L79-L111

**Comment by victoriaUW** [comment]
Step 1 completed - after extensive research on interfaces

**Comment by victoriaUW** [comment]
Step 2 - need to re go over exactly what is happening

**Comment by victoriaUW** [comment]
Step 4 complete - time to check

**Comment by victoriaUW** [comment]
Step 9/10 done -  will come back to step 7/8

**Comment by victoriaUW** [comment]
7/8 done :) only 10/11 to go!

**Comment by victoriaUW** [comment]
done :)

**Comment by lucassouzavieira** [comment]
Well done @victoriaUW ! 👏🏽 🎉
